services:
  db:
    image: postgres:16
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: local
      POSTGRES_DB: local
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
