name: Deploy to Production

on:
  push:
    # branches: [master]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      PUBLIC_POSTHOG_KEY: ${{ secrets.PUBLIC_POSTHOG_KEY }}
      PUBLIC_CI: false
      PUBLIC_DEV: false

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build

      - name: Decrypt SSH key
        id: ssh_key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ./encrypted_key
          openssl rsa -in ./encrypted_key -out ./decrypted_key -passin pass:"${{ secrets.SSH_KEY_PASSPHRASE }}"
          chmod 600 ./decrypted_key
          echo "key=$(cat ./decrypted_key)" >> $GITHUB_OUTPUT

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ steps.ssh_key.outputs.key }}
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}

      - name: Deploy to DigitalOcean
        env:
          DEPLOY_PATH: /var/www/tasken
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
          DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
        run: |
          # Sync build files
          rsync -avz --delete ./build/ $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH/build/
          rsync -avz package*.json $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH/

          # Run remote deployment commands
          ssh $DEPLOY_USER@$DEPLOY_HOST "\
            cd $DEPLOY_PATH && \
            npm ci --production && \
            pm2 reload tasken || pm2 start build/index.js --name tasken && \
            sudo systemctl reload nginx"
