name: Deploy to Production

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      BASE_URL: https://tasken.app
      RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
      PUBLIC_POSTHOG_KEY: ${{ secrets.PUBLIC_POSTHOG_KEY }}
      PUBLIC_CI: false
      PUBLIC_DEV: false
      PUBLIC_WS_URL: wss://tasken.app/ws/

    steps:
      - uses: actions/checkout@v4

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}

      - name: Deploy to DigitalOcean
        env:
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
          DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
        run: |
          rsync -avz --delete --exclude 'node_modules' --exclude '.git' ./ $DEPLOY_USER@$DEPLOY_HOST:~/tasken

          ssh $DEPLOY_USER@$DEPLOY_HOST "\
            export DATABASE_URL="${{ secrets.DATABASE_URL }}" && \
            export BASE_URL="https://tasken.app" && \
            export RESEND_API_KEY="${{ secrets.RESEND_API_KEY }}" && \
            export PUBLIC_POSTHOG_KEY=${{ secrets.PUBLIC_POSTHOG_KEY }} && \
            export PUBLIC_WS_URL='wss://tasken.app/ws/' && \
            export PUBLIC_CI=false && \
            export PUBLIC_DEV=false && \
            export NVM_DIR=~/.nvm && \
            source \$NVM_DIR/nvm.sh && \
            nvm use 22 && \
            npm install -g pm2 tsx && \
            cd ~/tasken && \
            ls -la && \
            npm install --omit=dev && \
            npm install @rollup/rollup-linux-x64-gnu --save-optional && \
            npm run build && \
            BASE_URL='https://tasken.app' RESEND_API_KEY='${{ secrets.RESEND_API_KEY }}' DATABASE_URL='${{ secrets.DATABASE_URL }}' PUBLIC_WS_URL='wss://tasken.app/ws/' PUBLIC_POSTHOG_KEY=${{ secrets.PUBLIC_POSTHOG_KEY }} PUBLIC_DEV=false PUBLIC_CI=false npm run db:migrate:run && \
            BASE_URL='https://tasken.app' RESEND_API_KEY='${{ secrets.RESEND_API_KEY }}' DATABASE_URL='${{ secrets.DATABASE_URL }}' PUBLIC_WS_URL='wss://tasken.app/ws/' PUBLIC_POSTHOG_KEY=${{ secrets.PUBLIC_POSTHOG_KEY }} PUBLIC_DEV=false PUBLIC_CI=false PUBLIC_WS_URL='wss://tasken.app/ws/' pm2 reload tasken --update-env || RESEND_API_KEY='${{ secrets.RESEND_API_KEY }}' BASE_URL='https://tasken.app' DATABASE_URL='${{ secrets.DATABASE_URL }}' PUBLIC_POSTHOG_KEY=${{ secrets.PUBLIC_POSTHOG_KEY }} PUBLIC_WS_URL='wss://tasken.app/ws/' PUBLIC_DEV=false PUBLIC_CI=false pm2 start build/index.js --name tasken && \
            sudo systemctl reload nginx"
